<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <RenderDicSourceRoot>$(MSBuildThisFileDirectory.TrimEnd('\'))</RenderDicSourceRoot>
  </PropertyGroup>

  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalOptions>/experimental:deterministic /pathmap:&quot;$(RenderDicSourceRoot)\renderdoc&quot;=R:\RenderDicSrc\core /pathmap:&quot;$(RenderDicSourceRoot)\qrenderdoc&quot;=R:\RenderDicSrc\ui /pathmap:&quot;$(RenderDicSourceRoot)\renderdoccmd&quot;=R:\RenderDicSrc\cmd /pathmap:&quot;$(RenderDicSourceRoot)\renderdocshim&quot;=R:\RenderDicSrc\shim /pathmap:&quot;$(RenderDicSourceRoot)&quot;=R:\RenderDicSrc %(AdditionalOptions)</AdditionalOptions>
    </ClCompile>
    <Link>
      <AdditionalOptions>/PDBALTPATH:%_PDB% %(AdditionalOptions)</AdditionalOptions>
    </Link>
  </ItemDefinitionGroup>
</Project>
