#!/usr/bin/env python3
# Generates qrenderdoc/Code/KernelInjector/driver_resources.h from the
# vulnerable driver binaries. The drivers are embedded so the packaged MSI
# does not need to ship loose .sys files and nothing is written next to the
# exe - the loader drops them into %TEMP% at runtime like kdmapper does.
#
# Usage:
#   python gen_driver_resource.py <input_dir> <output_header>
#   python gen_driver_resource.py ../vulnerable-drivers-main dist/driver_resources.h
#
# Input files (must exist in input_dir):
#   portwell.sys   - physical R/W backend driver
#   TBT_Force_Power_Control_Access64.sys - alternate backend driver
#   RenderDicInjector.sys - the built kernel_driver/ output; optional. When
#       missing an empty placeholder is emitted so the coordinator can report
#       a clear error instead of failing to compile.

import os
import sys


def emit_bytes(out, name, data):
    out.write("// %d bytes, generated by util/buildscripts/scripts/gen_driver_resource.py\n" % len(data))
    out.write("static const unsigned char %s[] = {\n" % name)
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        out.write("  " + ", ".join("0x%02X" % b for b in chunk) + ",\n")
    out.write("};\n")
    out.write("static const size_t %s_size = sizeof(%s);\n\n" % (name, name))


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        return 1

    input_dir, output_path = sys.argv[1], sys.argv[2]

    files = [
        ("portwell.sys", "portwell_driver_bytes"),
        ("TBT_Force_Power_Control_Access64.sys", "tbt_driver_bytes"),
    ]

    with open(output_path, "w", newline="\n") as out:
        out.write("/******************************************************************************\n")
        out.write(" * The MIT License (MIT)\n")
        out.write(" *\n")
        out.write(" * Copyright (c) 2014-2026 Baldur Karlsson\n")
        out.write(" *\n")
        out.write(" * Permission is hereby granted, free of charge, to any person obtaining a copy\n")
        out.write(" * of this software and associated documentation files (the \"Software\"), to deal\n")
        out.write(" * in the Software without restriction, including without limitation the rights\n")
        out.write(" * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n")
        out.write(" * copies of the Software, and to permit persons to whom the Software is\n")
        out.write(" * furnished to do so, subject to the following conditions:\n")
        out.write(" *\n")
        out.write(" * The above copyright notice and this permission notice shall be included in\n")
        out.write(" * all copies or substantial portions of the Software.\n")
        out.write(" *\n")
        out.write(" * THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n")
        out.write(" * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n")
        out.write(" * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n")
        out.write(" * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n")
        out.write(" * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n")
        out.write(" * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN\n")
        out.write(" * THE SOFTWARE.\n")
        out.write(" ******************************************************************************/\n\n")
        out.write("#pragma once\n\n")
        out.write("#include <cstddef>\n\n")
        out.write("// Embedded vulnerable driver images. Regenerate with\n")
        out.write("//   python util/buildscripts/scripts/gen_driver_resource.py <input_dir> <output>\n\n")

        for filename, name in files:
            path = os.path.join(input_dir, filename)
            if not os.path.exists(path):
                print("error: %s not found in %s" % (filename, input_dir))
                return 1
            with open(path, "rb") as f:
                data = f.read()
            emit_bytes(out, name, data)

        # Optional: the built injection driver. Emit a single-byte placeholder
        # when missing so the build still succeeds (a zero-length array is a
        # compiler extension and fails on MSVC; the runtime size check in
        # manual_map reports a clear error either way).
        injector_path = os.path.join(input_dir, "RenderDicInjector.sys")
        if os.path.exists(injector_path):
            with open(injector_path, "rb") as f:
                injector = f.read()
            print("embedded RenderDicInjector.sys (%d bytes)" % len(injector))
        else:
            injector = b"\x00"
            print("warning: RenderDicInjector.sys not found, emitting 1-byte placeholder - "
                  "build kernel_driver/ and regenerate before packaging")
        emit_bytes(out, "injector_driver_bytes", injector)

    print("wrote %s (%d bytes total)" % (output_path, sum(
        os.path.getsize(os.path.join(input_dir, f)) for f, _ in files)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
